# A. Load df_ml

In [1]:
import pandas as pd

In [2]:
# 1. df3 laden – aus deinem Projektordner
df3 = pd.read_csv(
    r"C:\_AA-LapTop-MSIT\_MyMSIT_MasteryProject_Term7\01_data\processed\STEP2und3_df_kundensegmentierung_regelbasiert.csv"
)

In [5]:
# Restmenge für ML: nur Nutzer ohne regelbasiertes Segment
df_ml = df3[df3["segment_rule"].isna()].copy()

In [8]:
# Schnellcheck
print("df3 shape:", df3.shape)
print("df_ml shape:", df_ml.shape)

df_ml.head()

df3 shape: (5782, 29)
df_ml shape: (4371, 29)

,sessions_ttl,clicks_avg,cancellations_ttl,flights_booked_ttl,hotels_booked_ttl,nightsPerTrip_avg,lead_time_flight_days_avg,lead_time_flight_days_std,business_weekday_rate,hotel_discount_proportion_avg,...,revenue_total_user,total_discount_savings,climate_segment_mode_kalt_reise,climate_segment_mode_klimaneutral,climate_segment_mode_tropen_reise,climate_segment_mode_warm_reise,distance_category_mode_global,distance_category_mode_lokal,distance_category_mode_regional,segment_rule
0,8,9.125,0,2.0,2.0,1.000000,6.500000,2.121320,0.000000,0.0,...,1044.09,0.0,True,False,False,False,False,False,True,NaN
1,8,16.375,0,1.0,2.0,4.000000,9.000000,0.000000,0.000000,0.0,...,586.91,0.0,True,False,False,False,False,False,True,NaN
6,8,9.125,0,1.0,0.0,0.000000,6.000000,0.000000,0.000000,0.0,...,423.51,0.0,True,False,False,False,True,False,False,NaN
7,8,18.625,0,1.0,1.0,2.000000,8.000000,0.000000,1.000000,0.0,...,580.83,0.0,True,False,False,False,False,False,True,NaN
8,8,18.750,0,3.0,3.0,1.333333,8.666667,1.527525,0.333333,0.0,...,1277.87,0.0,True,False,False,False,False,False,True,NaN

# B. Feature‑Selection
* numerische Features extrahieren
* kategorische Features droppen
* segment_rule droppen

In [9]:
# segment_rule entfernen (ist nicht für ML geeignet)
df_ml_features = df_ml.drop(columns=["segment_rule"])

# Nur numerische Features behalten
df_ml_features = df_ml_features.select_dtypes(include=["number"])

# Schnellcheck
df_ml_features.info()
df_ml_features.head()

<class 'pandas.DataFrame'>
Index: 4371 entries, 0 to 5781
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   sessions_ttl                   4371 non-null   int64
 1   clicks_avg                     4371 non-null   float64
 2   cancellations_ttl              4371 non-null   int64
 3   flights_booked_ttl             4371 non-null   float64
 4   hotels_booked_ttl              4371 non-null   float64
 5   nightsPerTrip_avg              4371 non-null   float64
 6   lead_time_flight_days_avg      4371 non-null   float64
 7   lead_time_flight_days_std      4371 non-null   float64
 8   business_weekday_rate          4371 non-null   float64
 9   hotel_discount_proportion_avg  4371 non-null   float64
 10  hotel_discount_amount_avg      4371 non-null   float64
 11  winter_escape_rate             4371 non-null   float64
 12  recency_days_flight            4371 non-null   float64
 13  unique_destinations_count      4371 non-null   float64
 14  winter_travel_rate             4371 non-null   float64
 15  summer_travel_rate             4371 non-null   float64
 16  hotel_price_avg                4371 non-null   float64
 17  tropics_rate                   4371 non-null   float64
 18  trips_per_active_month         4371 non-null   float64
 19  revenue_total_user             4371 non-null   float64
 20  total_discount_savings         4371 non-null   float64
dtypes: float64(19), int64(2)
memory usage: 880.3 KB

,sessions_ttl,clicks_avg,cancellations_ttl,flights_booked_ttl,hotels_booked_ttl,nightsPerTrip_avg,lead_time_flight_days_avg,lead_time_flight_days_std,business_weekday_rate,hotel_discount_proportion_avg,...,winter_escape_rate,recency_days_flight,unique_destinations_count,winter_travel_rate,summer_travel_rate,hotel_price_avg,tropics_rate,trips_per_active_month,revenue_total_user,total_discount_savings
0,8,9.125,0,2.0,2.0,1.000000,6.500000,2.121320,0.000000,0.0,...,0.0,456.0,2.0,0.000000,0.000000,90.0,0.5,1.0,1044.09,0.0
1,8,16.375,0,1.0,2.0,4.000000,9.000000,0.000000,0.000000,0.0,...,0.0,401.0,1.0,0.000000,1.000000,198.5,0.0,1.0,586.91,0.0
6,8,9.125,0,1.0,0.0,0.000000,6.000000,0.000000,0.000000,0.0,...,0.0,470.0,1.0,0.000000,0.000000,0.0,0.0,1.0,423.51,0.0
7,8,18.625,0,1.0,1.0,2.000000,8.000000,0.000000,1.000000,0.0,...,0.0,397.0,1.0,0.000000,1.000000,213.0,0.0,1.0,580.83,0.0
8,8,18.750,0,3.0,3.0,1.333333,8.666667,1.527525,0.333333,0.0,...,0.0,350.0,3.0,0.333333,0.333333,207.0,0.0,1.0,1277.87,0.0

# C. Scaling

# D. Optional: PCA

# E. Clustering
* KMeans
* DBSCAN
* HDBSCAN
* Silhouette‑Score
* Elbow‑Method

# F. Cluster interpretieren
* Feature‑Mittelwerte pro Cluster
* Heatmaps
* Radar‑Charts

# G. Cluster benennen